version: "3.8"

services:
  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - "5455:5432"
    volumes:
      - ./volumes/inventory_db:/var/lib/postgresql/data
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
