CREATE DATABASE product_db WITH OWNER = myuser ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE warehouse_db WITH OWNER = myuser ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE order_db WITH OWNER = myuser ENCODING = 'UTF8' CONNECTION LIMIT = -1;
